# Generated by Django 2.2.4 on 2023-02-23 14:48

from django.db import migrations, models
import fadderanmalan.models


class Migration(migrations.Migration):

    dependencies = [
        ('fadderanmalan', '0025_delete_leavequeue'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='oneway_locked',
            field=models.BooleanField(default=False, help_text='Om jobbet ska vara envägslåst. Överskrider datumen nedan.', verbose_name='One-way locked'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='oneway_locked_after',
            field=models.DateField(default=fadderanmalan.models.default_oneway_locked_after, help_text='Dagen EFTER detta datum kommer jobbet att låsas.'),
        ),
        migrations.AddField(
            model_name='job',
            name='oneway_locked_until',
            field=models.DateField(default=fadderanmalan.models.default_oneway_locked_until, help_text='Jobbet kommer att låsas upp FRÅN OCH MED detta datum.'),
        ),
    ]
