# Generated by Django 2.2.4 on 2023-07-27 11:41

from django.db import migrations, models
import fadderanmalan.models


class Migration(migrations.Migration):

    dependencies = [
        ('fadderanmalan', '0026_auto_20230223_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='oneway_locked_after',
            field=models.DateField(default=fadderanmalan.models.default_oneway_locked_after, help_text='Dagen EFTER detta datum kommer jobbet att låsas.', verbose_name='One-way locked after'),
        ),
        migrations.AlterField(
            model_name='job',
            name='oneway_locked_until',
            field=models.DateField(default=fadderanmalan.models.default_oneway_locked_until, help_text='Jobbet kommer att låsas upp FRÅN OCH MED detta datum.', verbose_name='One-way locked until'),
        ),
    ]
