# Generated by Django 2.2.4 on 2020-04-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190705_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='bonus_points',
            field=models.ManyToManyField(to='accounts.BonusPoints'),
        ),
    ]
