# Generated by Django 2.2.4 on 2020-04-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200404_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bonus_points',
            field=models.ManyToManyField(blank=True, to='accounts.BonusPoints'),
        ),
    ]
